package com.tincent.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.tincent.dao.MotionType;
import com.tincent.dao.MotionRecord;

import com.tincent.dao.MotionTypeDao;
import com.tincent.dao.MotionRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig motionTypeDaoConfig;
    private final DaoConfig motionRecordDaoConfig;

    private final MotionTypeDao motionTypeDao;
    private final MotionRecordDao motionRecordDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        motionTypeDaoConfig = daoConfigMap.get(MotionTypeDao.class).clone();
        motionTypeDaoConfig.initIdentityScope(type);

        motionRecordDaoConfig = daoConfigMap.get(MotionRecordDao.class).clone();
        motionRecordDaoConfig.initIdentityScope(type);

        motionTypeDao = new MotionTypeDao(motionTypeDaoConfig, this);
        motionRecordDao = new MotionRecordDao(motionRecordDaoConfig, this);

        registerDao(MotionType.class, motionTypeDao);
        registerDao(MotionRecord.class, motionRecordDao);
    }
    
    public void clear() {
        motionTypeDaoConfig.getIdentityScope().clear();
        motionRecordDaoConfig.getIdentityScope().clear();
    }

    public MotionTypeDao getMotionTypeDao() {
        return motionTypeDao;
    }

    public MotionRecordDao getMotionRecordDao() {
        return motionRecordDao;
    }

}
