package com.tincent.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.tincent.dao.MotionType;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MOTION_TYPE".
*/
public class MotionTypeDao extends AbstractDao<MotionType, Long> {

    public static final String TABLENAME = "MOTION_TYPE";

    /**
     * Properties of entity MotionType.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PlanId = new Property(1, String.class, "PlanId", false, "PLAN_ID");
        public final static Property PatientId = new Property(2, String.class, "PatientId", false, "PATIENT_ID");
        public final static Property PlanTypeId = new Property(3, String.class, "PlanTypeId", false, "PLAN_TYPE_ID");
        public final static Property PlanTypeName = new Property(4, String.class, "PlanTypeName", false, "PLAN_TYPE_NAME");
        public final static Property MotionTypeId = new Property(5, String.class, "MotionTypeId", false, "MOTION_TYPE_ID");
        public final static Property MotionTypeName = new Property(6, String.class, "MotionTypeName", false, "MOTION_TYPE_NAME");
        public final static Property MotionDuration = new Property(7, int.class, "MotionDuration", false, "MOTION_DURATION");
        public final static Property MotionInterval = new Property(8, int.class, "MotionInterval", false, "MOTION_INTERVAL");
        public final static Property MotionFrequency = new Property(9, int.class, "MotionFrequency", false, "MOTION_FREQUENCY");
        public final static Property ReservedOne = new Property(10, String.class, "ReservedOne", false, "RESERVED_ONE");
        public final static Property ReservedTwo = new Property(11, String.class, "ReservedTwo", false, "RESERVED_TWO");
    };


    public MotionTypeDao(DaoConfig config) {
        super(config);
    }
    
    public MotionTypeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MOTION_TYPE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"PLAN_ID\" TEXT NOT NULL ," + // 1: PlanId
                "\"PATIENT_ID\" TEXT NOT NULL ," + // 2: PatientId
                "\"PLAN_TYPE_ID\" TEXT NOT NULL ," + // 3: PlanTypeId
                "\"PLAN_TYPE_NAME\" TEXT NOT NULL ," + // 4: PlanTypeName
                "\"MOTION_TYPE_ID\" TEXT NOT NULL ," + // 5: MotionTypeId
                "\"MOTION_TYPE_NAME\" TEXT NOT NULL ," + // 6: MotionTypeName
                "\"MOTION_DURATION\" INTEGER NOT NULL ," + // 7: MotionDuration
                "\"MOTION_INTERVAL\" INTEGER NOT NULL ," + // 8: MotionInterval
                "\"MOTION_FREQUENCY\" INTEGER NOT NULL ," + // 9: MotionFrequency
                "\"RESERVED_ONE\" TEXT NOT NULL ," + // 10: ReservedOne
                "\"RESERVED_TWO\" TEXT NOT NULL );"); // 11: ReservedTwo
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MOTION_TYPE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, MotionType entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getPlanId());
        stmt.bindString(3, entity.getPatientId());
        stmt.bindString(4, entity.getPlanTypeId());
        stmt.bindString(5, entity.getPlanTypeName());
        stmt.bindString(6, entity.getMotionTypeId());
        stmt.bindString(7, entity.getMotionTypeName());
        stmt.bindLong(8, entity.getMotionDuration());
        stmt.bindLong(9, entity.getMotionInterval());
        stmt.bindLong(10, entity.getMotionFrequency());
        stmt.bindString(11, entity.getReservedOne());
        stmt.bindString(12, entity.getReservedTwo());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public MotionType readEntity(Cursor cursor, int offset) {
        MotionType entity = new MotionType( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // PlanId
            cursor.getString(offset + 2), // PatientId
            cursor.getString(offset + 3), // PlanTypeId
            cursor.getString(offset + 4), // PlanTypeName
            cursor.getString(offset + 5), // MotionTypeId
            cursor.getString(offset + 6), // MotionTypeName
            cursor.getInt(offset + 7), // MotionDuration
            cursor.getInt(offset + 8), // MotionInterval
            cursor.getInt(offset + 9), // MotionFrequency
            cursor.getString(offset + 10), // ReservedOne
            cursor.getString(offset + 11) // ReservedTwo
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, MotionType entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPlanId(cursor.getString(offset + 1));
        entity.setPatientId(cursor.getString(offset + 2));
        entity.setPlanTypeId(cursor.getString(offset + 3));
        entity.setPlanTypeName(cursor.getString(offset + 4));
        entity.setMotionTypeId(cursor.getString(offset + 5));
        entity.setMotionTypeName(cursor.getString(offset + 6));
        entity.setMotionDuration(cursor.getInt(offset + 7));
        entity.setMotionInterval(cursor.getInt(offset + 8));
        entity.setMotionFrequency(cursor.getInt(offset + 9));
        entity.setReservedOne(cursor.getString(offset + 10));
        entity.setReservedTwo(cursor.getString(offset + 11));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(MotionType entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(MotionType entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
