package com.tincent.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MOTION_TYPE".
 */
public class MotionType {

    private Long id;
    /** Not-null value. */
    private String PlanId;
    /** Not-null value. */
    private String PatientId;
    /** Not-null value. */
    private String PlanTypeId;
    /** Not-null value. */
    private String PlanTypeName;
    /** Not-null value. */
    private String MotionTypeId;
    /** Not-null value. */
    private String MotionTypeName;
    private int MotionDuration;
    private int MotionInterval;
    private int MotionFrequency;
    /** Not-null value. */
    private String ReservedOne;
    /** Not-null value. */
    private String ReservedTwo;

    public MotionType() {
    }

    public MotionType(Long id) {
        this.id = id;
    }

    public MotionType(Long id, String PlanId, String PatientId, String PlanTypeId, String PlanTypeName, String MotionTypeId, String MotionTypeName, int MotionDuration, int MotionInterval, int MotionFrequency, String ReservedOne, String ReservedTwo) {
        this.id = id;
        this.PlanId = PlanId;
        this.PatientId = PatientId;
        this.PlanTypeId = PlanTypeId;
        this.PlanTypeName = PlanTypeName;
        this.MotionTypeId = MotionTypeId;
        this.MotionTypeName = MotionTypeName;
        this.MotionDuration = MotionDuration;
        this.MotionInterval = MotionInterval;
        this.MotionFrequency = MotionFrequency;
        this.ReservedOne = ReservedOne;
        this.ReservedTwo = ReservedTwo;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getPlanId() {
        return PlanId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPlanId(String PlanId) {
        this.PlanId = PlanId;
    }

    /** Not-null value. */
    public String getPatientId() {
        return PatientId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPatientId(String PatientId) {
        this.PatientId = PatientId;
    }

    /** Not-null value. */
    public String getPlanTypeId() {
        return PlanTypeId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPlanTypeId(String PlanTypeId) {
        this.PlanTypeId = PlanTypeId;
    }

    /** Not-null value. */
    public String getPlanTypeName() {
        return PlanTypeName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPlanTypeName(String PlanTypeName) {
        this.PlanTypeName = PlanTypeName;
    }

    /** Not-null value. */
    public String getMotionTypeId() {
        return MotionTypeId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMotionTypeId(String MotionTypeId) {
        this.MotionTypeId = MotionTypeId;
    }

    /** Not-null value. */
    public String getMotionTypeName() {
        return MotionTypeName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMotionTypeName(String MotionTypeName) {
        this.MotionTypeName = MotionTypeName;
    }

    public int getMotionDuration() {
        return MotionDuration;
    }

    public void setMotionDuration(int MotionDuration) {
        this.MotionDuration = MotionDuration;
    }

    public int getMotionInterval() {
        return MotionInterval;
    }

    public void setMotionInterval(int MotionInterval) {
        this.MotionInterval = MotionInterval;
    }

    public int getMotionFrequency() {
        return MotionFrequency;
    }

    public void setMotionFrequency(int MotionFrequency) {
        this.MotionFrequency = MotionFrequency;
    }

    /** Not-null value. */
    public String getReservedOne() {
        return ReservedOne;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setReservedOne(String ReservedOne) {
        this.ReservedOne = ReservedOne;
    }

    /** Not-null value. */
    public String getReservedTwo() {
        return ReservedTwo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setReservedTwo(String ReservedTwo) {
        this.ReservedTwo = ReservedTwo;
    }

}
