package com.tincent.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MOTION_RECORD".
 */
public class MotionRecord {

    private Long id;
    /** Not-null value. */
    private String PlanId;
    /** Not-null value. */
    private String PatientId;
    /** Not-null value. */
    private String PlanTypeId;
    /** Not-null value. */
    private String PlanTypeName;
    /** Not-null value. */
    private String MotionTypeId;
    /** Not-null value. */
    private String MotionTypeName;
    /** Not-null value. */
    private java.util.Date MotionDay;
    private int MotionDuration;
    /** Not-null value. */
    private String MotionWeek;

    public MotionRecord() {
    }

    public MotionRecord(Long id) {
        this.id = id;
    }

    public MotionRecord(Long id, String PlanId, String PatientId, String PlanTypeId, String PlanTypeName, String MotionTypeId, String MotionTypeName, java.util.Date MotionDay, int MotionDuration, String MotionWeek) {
        this.id = id;
        this.PlanId = PlanId;
        this.PatientId = PatientId;
        this.PlanTypeId = PlanTypeId;
        this.PlanTypeName = PlanTypeName;
        this.MotionTypeId = MotionTypeId;
        this.MotionTypeName = MotionTypeName;
        this.MotionDay = MotionDay;
        this.MotionDuration = MotionDuration;
        this.MotionWeek = MotionWeek;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getPlanId() {
        return PlanId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPlanId(String PlanId) {
        this.PlanId = PlanId;
    }

    /** Not-null value. */
    public String getPatientId() {
        return PatientId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPatientId(String PatientId) {
        this.PatientId = PatientId;
    }

    /** Not-null value. */
    public String getPlanTypeId() {
        return PlanTypeId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPlanTypeId(String PlanTypeId) {
        this.PlanTypeId = PlanTypeId;
    }

    /** Not-null value. */
    public String getPlanTypeName() {
        return PlanTypeName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPlanTypeName(String PlanTypeName) {
        this.PlanTypeName = PlanTypeName;
    }

    /** Not-null value. */
    public String getMotionTypeId() {
        return MotionTypeId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMotionTypeId(String MotionTypeId) {
        this.MotionTypeId = MotionTypeId;
    }

    /** Not-null value. */
    public String getMotionTypeName() {
        return MotionTypeName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMotionTypeName(String MotionTypeName) {
        this.MotionTypeName = MotionTypeName;
    }

    /** Not-null value. */
    public java.util.Date getMotionDay() {
        return MotionDay;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMotionDay(java.util.Date MotionDay) {
        this.MotionDay = MotionDay;
    }

    public int getMotionDuration() {
        return MotionDuration;
    }

    public void setMotionDuration(int MotionDuration) {
        this.MotionDuration = MotionDuration;
    }

    /** Not-null value. */
    public String getMotionWeek() {
        return MotionWeek;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMotionWeek(String MotionWeek) {
        this.MotionWeek = MotionWeek;
    }

}
