package com.tincent.dao;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "NOTE_RECORD".
 */
public class NoteRecord implements Serializable {

    private Long id;
    /** Not-null value. */
    private String NoteTitle;
    /** Not-null value. */
    private String NoteAuthor;
    /** Not-null value. */
    private String NoteContent;
    private long TimeStamp;
    /** Not-null value. */
    private java.util.Date CreateTime;
    /** Not-null value. */
    private java.util.Date UpdateTime;

    public NoteRecord() {
    }

    public NoteRecord(Long id) {
        this.id = id;
    }

    public NoteRecord(Long id, String NoteTitle, String NoteAuthor, String NoteContent, long TimeStamp, java.util.Date CreateTime, java.util.Date UpdateTime) {
        this.id = id;
        this.NoteTitle = NoteTitle;
        this.NoteAuthor = NoteAuthor;
        this.NoteContent = NoteContent;
        this.TimeStamp = TimeStamp;
        this.CreateTime = CreateTime;
        this.UpdateTime = UpdateTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getNoteTitle() {
        return NoteTitle;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNoteTitle(String NoteTitle) {
        this.NoteTitle = NoteTitle;
    }

    /** Not-null value. */
    public String getNoteAuthor() {
        return NoteAuthor;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNoteAuthor(String NoteAuthor) {
        this.NoteAuthor = NoteAuthor;
    }

    /** Not-null value. */
    public String getNoteContent() {
        return NoteContent;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNoteContent(String NoteContent) {
        this.NoteContent = NoteContent;
    }

    public long getTimeStamp() {
        return TimeStamp;
    }

    public void setTimeStamp(long TimeStamp) {
        this.TimeStamp = TimeStamp;
    }

    /** Not-null value. */
    public java.util.Date getCreateTime() {
        return CreateTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreateTime(java.util.Date CreateTime) {
        this.CreateTime = CreateTime;
    }

    /** Not-null value. */
    public java.util.Date getUpdateTime() {
        return UpdateTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUpdateTime(java.util.Date UpdateTime) {
        this.UpdateTime = UpdateTime;
    }

}
